[package]
name = "day7b"
version = "0.1.0"
authors = ["Michael <michael@thorpe.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"
